name: Appstore CI

on:
  push:
    tags:
      - "appstore-*"

jobs:
  storebuild:
    runs-on: ubuntu-latest

    steps:
    - name: Check out my other private repo
      uses: actions/checkout@master
      with:
        repository: CoolBank/wallet_android
        token: ${{ secrets.MY_PAT }}
        
    - name: Checkout main-store
      run: |
          git pull
          git checkout -b main-store-google origin/main-store-google
          
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    
    - name: Config ssh
      run: bash ${GITHUB_WORKSPACE}/.github/scripts/ssh_config.sh 
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      env:
          KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
          STOREPASSWORD: ${{ secrets.STOREPASSWORD }}
          KEYALIAS: ${{ secrets.KEYALIAS }}
      run: |
          sed -i "1s/123/$KEYPASSWORD/" key.properties
          sed -i "2s/123/$STOREPASSWORD/" key.properties
          sed -i "3s/123/$KEYALIAS/" key.properties
          bash ./gradlew assembleAppstoreRelease --stacktrace
          
    - uses: actions/upload-artifact@v2
      with:
          name: app
          path: app/build/outputs/apk/appstore/release/app-appstore-release.apk 

    - uses: r0adkll/upload-google-play@v1
      with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_KEY }}
          packageName: com.coinhub.wallet
          releaseFiles: app/build/outputs/apk/appstore/release/app-appstore-release.apk 
          track: production
          status: completed
          inAppUpdatePriority: 2
          whatsNewDirectory: releaseNotes/
